Develop
whtsky/jotang.party pull request #3
Opened 2017-09-06 07:58 UTC by Agrimonia

网站基本上成型了部分链接还没挂上，成员信息有些不全

2017-09-06 08:34 UTC, whtsky commented
.DS_Store 怎么都传上来了…
话说 Font Awesome 和 jQuery 全家桶走 CDN 吼不吼啊

2017-09-06 08:36 UTC, Agrimonia commented
吼啊
发自网易邮箱大师
在2017年09月06日 16:34，Wu Haotian 写道： .DS_Store 怎么都传上来了…
话说 Font Awesome 和 jQuery 全家桶走 CDN 吼不吼啊

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JoTang/jotang.party","title":"JoTang/jotang.party","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JoTang/jotang.party"}},"updates":{"snippets":[{"icon":"PERSON","message":"@whtsky in #3: .DS_Store 怎么都传上来了…\r\n话说 Font Awesome 和 jQuery 全家桶走 CDN 吼不吼啊"}],"action":{"name":"View Pull Request","url":"https://github.com/JoTang/jotang.party/pull/3#issuecomment-327414837"}}}

2017-09-11 16:07 UTC, Agrimonia commented
忐忑不安。。。

2017-09-11 16:14 UTC, Agrimonia commented
感觉CDN这里没有改清楚

2017-09-11 17:03 UTC, Agrimonia commented
是不是一旦推上了就改不了了。。。

2017-09-13 05:29 UTC, whtsky requested changes
https://github.com/JoTang/jotang.party/pull/3/files#diff-291e507647ffbab8010da14e7d4e99ceR144
缩进

2017-09-13 11:17 UTC, whtsky approved these changes

2017-09-13 16:45 UTC, merged